### ISSUE TITLE
Cannot call indexOf of undefined

### ISSUE THREAD

**Issue by IonicaBizau** [jxmono/crud#42]
Saw this on production:

``` sh
[Tue Oct 21 2014 15:25:16 GMT+0000 (UTC)] Error: TypeError: Cannot call method 'indexOf' of undefined
    at /home/mono/mono/apps/crm_hf78HGT965HgtB96KJyg9dfGHtgV/mono_custom/listen.js:342:26
    at /home/mono/mono/apps/crm_hf78HGT965HgtB96KJyg9dfGHtgV/mono_modules/github/jillix/crud/v0.3.3/operations.js:40:25
    at /home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/cursor.js:172:16
    at commandHandler (/home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/cursor.js:720:16)
    at /home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/db.js:1911:9
    at Server.Base._callHandler (/home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/mono/mono/node_modules/modm/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:95:17)
```

**Comment by IonicaBizau** [comment]
Let's hope this was fixed in the latest versions...

**Comment by gabipetrovay** [comment]
:laughing: interesting bug solving :stuck_out_tongue_winking_eye:

**Comment by IonicaBizau** [comment]
See? Sometimes time fixes the things. :smile:

**Comment by gabipetrovay** [comment]
Time heals almost every wound!
